# Generated by Django 4.2.7 on 2023-11-20 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_professional_bio_alter_professional_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='booked',
        ),
    ]
