# Generated by Django 5.0 on 2023-12-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_appointment_professional'),
        ('staff', '0003_remove_slot_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='professional',
        ),
        migrations.AddField(
            model_name='slot',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Professional',
        ),
    ]
