# Generated by Django 4.2.7 on 2023-11-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=10, unique=True, verbose_name='phone')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('password_created', models.DateTimeField(auto_now=True, verbose_name='password_created')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
