# Generated by Django 4.2.7 on 2023-11-29 18:48

import customauth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0004_remove_user_role_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', customauth.models.UserManager()),
            ],
        ),
    ]
