# Generated by Django 4.2.7 on 2023-11-15 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0002_addon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addons', models.ManyToManyField(blank=True, to='service.addon')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='staff.professional')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.slot')),
                ('subservice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.subservice')),
            ],
        ),
    ]
