# Generated by Django 4.2.7 on 2023-11-17 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_addon'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='client',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='subservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='service.subservice'),
        ),
    ]
