# Generated by Django 4.2.7 on 2023-11-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_addon_image_url_alter_service_image_url_and_more'),
        ('booking', '0002_rename_client_appointment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='addons',
            field=models.ManyToManyField(to='service.addon'),
        ),
    ]
