# Generated by Django 5.0 on 2023-12-19 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_appointment_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='professional',
        ),
    ]
