# Generated by Django 4.2.7 on 2023-11-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_addon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='image_url',
            field=models.ImageField(null=True, upload_to='addon'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_url',
            field=models.ImageField(null=True, upload_to='service'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='image_url',
            field=models.ImageField(null=True, upload_to='subservice'),
        ),
    ]
